development:
  clients:
    default:
      uri: <%= ENV['DATABASE_URL_DEV'] %>
      options:
  options:
test:
  clients:
    default:
      uri: <%= ENV['DATABASE_URL_TEST'] %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      uri: <%= ENV['DATABASE_URL'] %>
